#!/usr/bin/env python3
"""Extract CLAM-compatible feature bags from multi-source DICOM WSI slides.

Coordinates are read from a manifest generated by build_dicom_feature_manifest.py.
They are always level-0 coordinates. The reader selects the largest tiled VOLUME
DICOM group in each slide directory and supports a level-0 image split across
multiple DICOM instances.
"""

from __future__ import annotations

import argparse
import csv
import math
import os
import re
from dataclasses import dataclass
from io import BytesIO
from pathlib import Path
from typing import Iterable

import h5py
import numpy as np
import pydicom
import torch
from PIL import Image
from pydicom.encaps import get_frame

from models import get_encoder


@dataclass(frozen=True)
class FrameRef:
    source_path: Path
    frame_index: int


@dataclass(frozen=True)
class SlideSpec:
    case_id: str
    slide_id: str
    slide_rel_path: str
    coords_source: str
    coords_path: Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset-root", type=Path, required=True)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--feat-dir", type=Path, required=True)
    parser.add_argument(
        "--model-name",
        default="resnet50_trunc",
        choices=["resnet50_trunc", "uni_v1", "uni_v2", "uni_v2_l", "conch_v1", "conch_v1_5"],
    )
    parser.add_argument("--target-patch-size", type=int, default=224)
    parser.add_argument("--batch-size", type=int, default=128)
    parser.add_argument("--device", choices=["auto", "cuda", "cpu"], default="auto")
    parser.add_argument("--amp", action="store_true", help="Use FP16 autocast on CUDA.")
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument(
        "--max-patches-per-slide",
        type=int,
        default=None,
        help="Encode at most this many reproducibly sampled patches per slide. Use only for smoke tests.",
    )
    parser.add_argument("--sample-seed", type=int, default=0)
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def resolve_path(path: Path, dataset_root: Path) -> Path:
    return path if path.is_absolute() else dataset_root / path


def is_volume_wsi(dataset: pydicom.Dataset) -> bool:
    image_type = [str(value).upper() for value in getattr(dataset, "ImageType", [])]
    return "VOLUME" in image_type and hasattr(dataset, "TotalPixelMatrixColumns")


def choose_level0_dicom_group(slide_dir: Path) -> tuple[Path, ...]:
    grouped: dict[tuple[int, int, int, int, int], list[Path]] = {}
    for path in sorted(slide_dir.glob("*.dcm")):
        try:
            dataset = pydicom.dcmread(str(path), stop_before_pixels=True, force=True)
        except Exception:
            continue
        if not is_volume_wsi(dataset):
            continue
        total_w = int(dataset.TotalPixelMatrixColumns)
        total_h = int(dataset.TotalPixelMatrixRows)
        key = (total_w * total_h, total_w, total_h, int(dataset.Rows), int(dataset.Columns))
        grouped.setdefault(key, []).append(path)
    if not grouped:
        return ()
    return tuple(sorted(grouped[max(grouped, key=lambda key: key[0])]))


def frame_positions(
    dataset: pydicom.Dataset, *, sequential_offset: int | None = None
) -> list[tuple[int, int]]:
    rows = int(dataset.Rows)
    columns = int(dataset.Columns)
    total_w = int(dataset.TotalPixelMatrixColumns)
    total_h = int(dataset.TotalPixelMatrixRows)
    n_frames = int(dataset.NumberOfFrames)
    tile_columns = math.ceil(total_w / columns)
    tile_rows = math.ceil(total_h / rows)

    if tile_columns * tile_rows == n_frames:
        return [
            ((index % tile_columns) * columns, (index // tile_columns) * rows)
            for index in range(n_frames)
        ]
    if sequential_offset is not None:
        return [
            (
                ((sequential_offset + index) % tile_columns) * columns,
                ((sequential_offset + index) // tile_columns) * rows,
            )
            for index in range(n_frames)
        ]

    per_frame = getattr(dataset, "PerFrameFunctionalGroupsSequence", None)
    if per_frame is None or len(per_frame) != n_frames:
        raise ValueError(
            f"Unexpected frame grid for {dataset.filename}: expected {tile_columns}x{tile_rows}, "
            f"found {n_frames} frames"
        )
    positions: list[tuple[int, int]] = []
    for frame_group in per_frame:
        plane_position = getattr(frame_group, "PlanePositionSlideSequence", None)
        if not plane_position:
            raise ValueError("DICOM frame has no PlanePositionSlideSequence")
        item = plane_position[0]
        positions.append(
            (
                int(item.ColumnPositionInTotalImagePixelMatrix) - 1,
                int(item.RowPositionInTotalImagePixelMatrix) - 1,
            )
        )
    return positions


class DicomLevel0Reader:
    """Random-access level-0 patch reader backed by tiled DICOM frames."""

    def __init__(self, slide_dir: Path):
        self.slide_dir = slide_dir
        self.paths = choose_level0_dicom_group(slide_dir)
        if not self.paths:
            raise ValueError(f"No tiled level-0 VOLUME DICOM found: {slide_dir}")

        metadata = [pydicom.dcmread(str(path), stop_before_pixels=True, force=True) for path in self.paths]
        first = metadata[0]
        self.total_w = int(first.TotalPixelMatrixColumns)
        self.total_h = int(first.TotalPixelMatrixRows)
        self.tile_h = int(first.Rows)
        self.tile_w = int(first.Columns)
        for path, dataset in zip(self.paths[1:], metadata[1:]):
            expected = (self.total_w, self.total_h, self.tile_h, self.tile_w)
            found = (
                int(dataset.TotalPixelMatrixColumns),
                int(dataset.TotalPixelMatrixRows),
                int(dataset.Rows),
                int(dataset.Columns),
            )
            if found != expected:
                raise ValueError(f"Mixed level-0 DICOM dimensions: {path}")

        total_grid_frames = math.ceil(self.total_w / self.tile_w) * math.ceil(
            self.total_h / self.tile_h
        )
        frame_counts = [int(dataset.NumberOfFrames) for dataset in metadata]
        sequential_group = len(self.paths) > 1 and sum(frame_counts) <= total_grid_frames
        self.tile_refs: dict[tuple[int, int], FrameRef] = {}
        decoded_offset = 0
        for path, dataset, frame_count in zip(self.paths, metadata, frame_counts):
            positions = frame_positions(
                dataset,
                sequential_offset=decoded_offset if sequential_group else None,
            )
            for index, (x0, y0) in enumerate(positions):
                key = (x0 // self.tile_w, y0 // self.tile_h)
                if key in self.tile_refs:
                    raise ValueError(f"Duplicate level-0 tile position {key} in {slide_dir}")
                self.tile_refs[key] = FrameRef(path, index)
            decoded_offset += frame_count

        self._pixel_dataset: pydicom.Dataset | None = None
        self._pixel_dataset_path: Path | None = None

    def _load_pixel_dataset(self, path: Path) -> pydicom.Dataset:
        if self._pixel_dataset_path != path:
            self._pixel_dataset = pydicom.dcmread(str(path), force=True)
            self._pixel_dataset_path = path
        assert self._pixel_dataset is not None
        return self._pixel_dataset

    def _read_tile(self, frame_ref: FrameRef) -> Image.Image:
        dataset = self._load_pixel_dataset(frame_ref.source_path)
        try:
            frame = get_frame(
                dataset.PixelData,
                frame_ref.frame_index,
                number_of_frames=int(dataset.NumberOfFrames),
            )
            return Image.open(BytesIO(frame)).convert("RGB")
        except Exception as exc:
            raise RuntimeError(
                f"Could not decode frame {frame_ref.frame_index} from {frame_ref.source_path}"
            ) from exc

    def read_patch(self, x: int, y: int, width: int, height: int) -> Image.Image:
        patch = Image.new("RGB", (width, height), "white")
        tile_x0 = max(0, x // self.tile_w)
        tile_y0 = max(0, y // self.tile_h)
        tile_x1 = min(math.ceil(self.total_w / self.tile_w) - 1, (x + width - 1) // self.tile_w)
        tile_y1 = min(math.ceil(self.total_h / self.tile_h) - 1, (y + height - 1) // self.tile_h)
        for tile_y in range(tile_y0, tile_y1 + 1):
            for tile_x in range(tile_x0, tile_x1 + 1):
                frame_ref = self.tile_refs.get((tile_x, tile_y))
                if frame_ref is None:
                    continue
                x0 = tile_x * self.tile_w
                y0 = tile_y * self.tile_h
                x1 = min(self.total_w, x0 + self.tile_w)
                y1 = min(self.total_h, y0 + self.tile_h)
                overlap_x0 = max(x, x0)
                overlap_y0 = max(y, y0)
                overlap_x1 = min(x + width, x1)
                overlap_y1 = min(y + height, y1)
                if overlap_x1 <= overlap_x0 or overlap_y1 <= overlap_y0:
                    continue
                tile = self._read_tile(frame_ref)
                crop = tile.crop(
                    (overlap_x0 - x0, overlap_y0 - y0, overlap_x1 - x0, overlap_y1 - y0)
                )
                patch.paste(crop, (overlap_x0 - x, overlap_y0 - y))
        return patch


def read_manifest(manifest_path: Path, dataset_root: Path) -> list[SlideSpec]:
    required = {"case_id", "slide_id", "slide_rel_path", "coords_source", "coords_rel_path"}
    specs: list[SlideSpec] = []
    seen_ids: set[str] = set()
    with manifest_path.open(newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        missing = required - set(reader.fieldnames or [])
        if missing:
            raise ValueError(f"Manifest is missing columns: {', '.join(sorted(missing))}")
        for row in reader:
            slide_id = row["slide_id"].strip()
            if not slide_id:
                continue
            if slide_id in seen_ids:
                raise ValueError(f"Duplicate slide_id in manifest: {slide_id}")
            if not re.fullmatch(r"[A-Za-z0-9._-]+", slide_id):
                raise ValueError(f"Unsafe slide_id: {slide_id}")
            seen_ids.add(slide_id)
            coords_path = Path(row["coords_rel_path"].strip())
            if not coords_path.is_absolute():
                coords_path = dataset_root / coords_path
            specs.append(
                SlideSpec(
                    case_id=row["case_id"].strip(),
                    slide_id=slide_id,
                    slide_rel_path=row["slide_rel_path"].strip().replace("\\", "/"),
                    coords_source=row["coords_source"].strip(),
                    coords_path=coords_path,
                )
            )
    return specs


def read_coordinates(coords_path: Path) -> tuple[np.ndarray, int]:
    with h5py.File(coords_path, "r") as handle:
        if "coords" not in handle:
            raise ValueError(f"No coords dataset: {coords_path}")
        raw_coords = np.asarray(handle["coords"])
        patch_size = int(handle.attrs.get("patch_size_level0", handle.attrs.get("patch_size", 256)))
    if raw_coords.ndim != 2 or raw_coords.shape[1] < 2:
        raise ValueError(f"coords must have at least x/y columns: {coords_path}")
    coords = np.asarray(raw_coords[:, :2], dtype=np.int32)
    if raw_coords.shape[1] >= 4:
        widths = np.unique(raw_coords[:, 2])
        heights = np.unique(raw_coords[:, 3])
        if len(widths) != 1 or len(heights) != 1 or int(widths[0]) != int(heights[0]):
            raise ValueError(f"Variable/non-square patch sizes are not supported: {coords_path}")
        patch_size = int(widths[0])
    if patch_size <= 0:
        raise ValueError(f"Invalid patch size in {coords_path}: {patch_size}")
    return coords, patch_size


def sample_coordinates(
    coords: np.ndarray,
    max_patches: int | None,
    seed: int,
) -> tuple[np.ndarray, int]:
    total_count = len(coords)
    if max_patches is None or max_patches >= total_count:
        return coords, total_count
    if max_patches < 1:
        raise ValueError("max_patches must be at least 1 when provided")
    indices = np.random.default_rng(seed).choice(total_count, size=max_patches, replace=False)
    return coords[np.sort(indices)], total_count


def output_paths(feat_dir: Path, slide_id: str) -> tuple[Path, Path]:
    return feat_dir / "h5_files" / f"{slide_id}.h5", feat_dir / "pt_files" / f"{slide_id}.pt"


def append_batch(
    output: h5py.File,
    features: np.ndarray,
    coords: np.ndarray,
) -> None:
    if "features" not in output:
        output.create_dataset(
            "features",
            shape=(0, features.shape[1]),
            maxshape=(None, features.shape[1]),
            chunks=(max(1, min(512, len(features))), features.shape[1]),
            compression="gzip",
            dtype=np.float32,
        )
        output.create_dataset(
            "coords",
            shape=(0, 2),
            maxshape=(None, 2),
            chunks=(max(1, min(512, len(coords))), 2),
            compression="gzip",
            dtype=np.int32,
        )
    for key, values in (("features", features), ("coords", coords)):
        dataset = output[key]
        start = len(dataset)
        dataset.resize(start + len(values), axis=0)
        dataset[start:] = values


def encode_slide(
    spec: SlideSpec,
    dataset_root: Path,
    h5_path: Path,
    pt_path: Path,
    model: torch.nn.Module,
    transform: object,
    device: torch.device,
    batch_size: int,
    amp: bool,
    max_patches: int | None,
    sample_seed: int,
) -> int:
    coords, patch_size = read_coordinates(spec.coords_path)
    coords, source_patch_count = sample_coordinates(coords, max_patches, sample_seed)
    if len(coords) == 0:
        raise ValueError(f"No selected patches: {spec.coords_path}")
    reader = DicomLevel0Reader(dataset_root / Path(spec.slide_rel_path))
    h5_path.parent.mkdir(parents=True, exist_ok=True)
    pt_path.parent.mkdir(parents=True, exist_ok=True)
    h5_tmp = h5_path.with_suffix(".h5.tmp")
    pt_tmp = pt_path.with_suffix(".pt.tmp")
    for path in (h5_tmp, pt_tmp):
        if path.exists():
            path.unlink()

    try:
        with h5py.File(h5_tmp, "w") as output:
            output.attrs["slide_id"] = spec.slide_id
            output.attrs["case_id"] = spec.case_id
            output.attrs["slide_rel_path"] = spec.slide_rel_path
            output.attrs["coords_source"] = spec.coords_source
            output.attrs["coords_path"] = str(spec.coords_path)
            output.attrs["patch_level"] = 0
            output.attrs["patch_size_level0"] = patch_size
            output.attrs["source_patch_count"] = source_patch_count
            output.attrs["encoded_patch_count"] = len(coords)
            output.attrs["patch_sampling"] = (
                "full" if len(coords) == source_patch_count else f"random_without_replacement(seed={sample_seed})"
            )
            output.attrs["source_dicom_paths"] = "|".join(str(path) for path in reader.paths)
            output.attrs["total_pixel_matrix"] = np.asarray([reader.total_w, reader.total_h])

            for start in range(0, len(coords), batch_size):
                coord_batch = coords[start : start + batch_size]
                images = [
                    transform(reader.read_patch(int(x), int(y), patch_size, patch_size))
                    for x, y in coord_batch
                ]
                inputs = torch.stack(images).to(device, non_blocking=device.type == "cuda")
                with torch.inference_mode():
                    with torch.autocast(device_type="cuda", enabled=amp and device.type == "cuda"):
                        features = model(inputs)
                if not isinstance(features, torch.Tensor):
                    raise TypeError(f"Encoder returned {type(features).__name__}, expected a tensor")
                append_batch(
                    output,
                    features.detach().cpu().float().numpy().astype(np.float32, copy=False),
                    coord_batch,
                )

        with h5py.File(h5_tmp, "r") as output:
            feature_tensor = torch.from_numpy(output["features"][:])
        torch.save(feature_tensor, pt_tmp)
        os.replace(h5_tmp, h5_path)
        os.replace(pt_tmp, pt_path)
    except Exception:
        for path in (h5_tmp, pt_tmp):
            if path.exists():
                path.unlink()
        raise
    return len(coords)


def write_failures(path: Path, failures: Iterable[dict[str, str]]) -> None:
    rows = list(failures)
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=["slide_id", "slide_rel_path", "error_type", "error_message"])
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    args = parse_args()
    dataset_root = args.dataset_root.expanduser().resolve()
    manifest_path = resolve_path(args.manifest, dataset_root)
    feat_dir = args.feat_dir.expanduser().resolve()
    if not manifest_path.is_file():
        raise FileNotFoundError(f"Manifest not found: {manifest_path}")
    if args.batch_size < 1:
        raise ValueError("--batch-size must be at least 1")
    if args.max_patches_per_slide is not None and args.max_patches_per_slide < 1:
        raise ValueError("--max-patches-per-slide must be at least 1")
    if args.device == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("--device cuda was requested but CUDA is unavailable")
    if args.device == "auto":
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    else:
        device = torch.device(args.device)

    specs = read_manifest(manifest_path, dataset_root)
    if args.limit is not None:
        specs = specs[: args.limit]
    print(f"Encoding manifest: {len(specs)} slide(s)")
    if args.dry_run:
        for spec in specs:
            coords, patch_size = read_coordinates(spec.coords_path)
            selected_coords, source_patch_count = sample_coordinates(
                coords, args.max_patches_per_slide, args.sample_seed
            )
            patch_count = (
                f"{len(selected_coords)} patches"
                if len(selected_coords) == source_patch_count
                else f"{len(selected_coords)}/{source_patch_count} sampled patches"
            )
            print(f"[DRY RUN] {spec.slide_id}: {patch_count}, size={patch_size}, {spec.coords_source}")
        return 0

    model, transform = get_encoder(args.model_name, target_img_size=args.target_patch_size)
    model = model.eval().to(device)
    failures: list[dict[str, str]] = []
    completed = 0
    skipped = 0
    for index, spec in enumerate(specs, start=1):
        h5_path, pt_path = output_paths(feat_dir, spec.slide_id)
        if not args.overwrite and h5_path.is_file() and pt_path.is_file():
            skipped += 1
            print(f"[SKIP] [{index}/{len(specs)}] {spec.slide_id}")
            continue
        try:
            count = encode_slide(
                spec,
                dataset_root,
                h5_path,
                pt_path,
                model,
                transform,
                device,
                args.batch_size,
                args.amp,
                args.max_patches_per_slide,
                args.sample_seed,
            )
            completed += 1
            print(f"[OK] [{index}/{len(specs)}] {spec.slide_id}: {count} patches")
        except Exception as exc:
            failures.append(
                {
                    "slide_id": spec.slide_id,
                    "slide_rel_path": spec.slide_rel_path,
                    "error_type": type(exc).__name__,
                    "error_message": str(exc),
                }
            )
            print(f"[FAIL] [{index}/{len(specs)}] {spec.slide_id}: {type(exc).__name__}: {exc}")

    failure_path = feat_dir / "logs" / "dicom_feature_failures.csv"
    write_failures(failure_path, failures)
    print(f"Completed: {completed}; skipped: {skipped}; failures: {len(failures)}")
    if failures:
        print(f"Failure log: {failure_path}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
